/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Solution;

import javax.swing.JButton;

/**
 *
 * @author AKIFHASAN
 */
public class Activity_5 extends javax.swing.JFrame {
    
   private String displayText = "", selectedOperation = "";
   private double inputOne=0, inputTwo=0, result=0;
   private boolean operatorPressed = false;

    /**
     * Creates new form Activity_5
     */
    public Activity_5() {
        initComponents();
        jTextField1.setEditable(false);
        
    }
    
    private void digitPressed(String digitStr){
       if(operatorPressed){
            inputOne = Double.parseDouble(displayText);
            jTextField1.setText("");
            displayText="";
            operatorPressed = false;
       }
          
       if(!(displayText.length()==0 && digitStr.equalsIgnoreCase("0"))){
            displayText = displayText + digitStr;
        }
        jTextField1.setText(displayText);
    }
    private void pointPressed(String digitStr){
       if(!displayText.contains(digitStr)){
            displayText = displayText + digitStr;
        }
        jTextField1.setText(displayText);
    }
    
    private void operatorPressed(String operator){
        if(displayText.length()!=0 && selectedOperation.equalsIgnoreCase("")){
            selectedOperation = operator;
        }
        else{
            if(!displayText.equalsIgnoreCase("")){
            inputTwo = Double.parseDouble(displayText);
            switch(selectedOperation){
                case "+":
                    result = inputOne + inputTwo;
                    break;
                case "-": 
                     result = inputOne - inputTwo;
                    break;
                case "/":
                     result = inputOne / inputTwo;
                    break;
                case "*":
                     result = inputOne *  inputTwo;
                    break;
                default:
                    break;
            }  
            selectedOperation = operator;
            displayText = Double.toString(result);
            jTextField1.setText(displayText);
            inputOne = result;
            inputTwo = 0;
        }
        operatorPressed = true;
        if(operator.equalsIgnoreCase("=")){
            inputOne=0;
        }
        }
        
    } 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ButtonSeven = new javax.swing.JButton();
        ButtonEight = new javax.swing.JButton();
        ButtonNine = new javax.swing.JButton();
        ButtonDivision = new javax.swing.JButton();
        ButtonFour = new javax.swing.JButton();
        ButtonFive = new javax.swing.JButton();
        ButtonSix = new javax.swing.JButton();
        ButtonMultiplication = new javax.swing.JButton();
        ButtonOne = new javax.swing.JButton();
        ButtonTwo = new javax.swing.JButton();
        ButtonThree = new javax.swing.JButton();
        ButtonSubtraction = new javax.swing.JButton();
        ButtonZero = new javax.swing.JButton();
        ButtonPoint = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonAddition = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        ButtonSeven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSeven.setText("7");
        ButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSevenActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSeven);

        ButtonEight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonEight.setText("8");
        ButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEightActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonEight);

        ButtonNine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonNine.setText("9");
        ButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNineActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonNine);

        ButtonDivision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonDivision.setText("/");
        ButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivisionActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonDivision);

        ButtonFour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonFour.setText("4");
        ButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFourActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonFour);

        ButtonFive.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonFive.setText("5");
        ButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFiveActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonFive);

        ButtonSix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSix.setText("6");
        ButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSixActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSix);

        ButtonMultiplication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonMultiplication.setText("*");
        ButtonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicationActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonMultiplication);

        ButtonOne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonOne.setText("1");
        ButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOneActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonOne);

        ButtonTwo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonTwo.setText("2");
        ButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTwoActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonTwo);

        ButtonThree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonThree.setText("3");
        ButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThreeActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonThree);

        ButtonSubtraction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSubtraction.setText("-");
        ButtonSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubtractionActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSubtraction);

        ButtonZero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonZero.setText("0");
        ButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonZeroActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonZero);

        ButtonPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPoint.setText(".");
        ButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPointActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonPoint);

        ButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonEqual.setText("=");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonEqual);

        ButtonAddition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonAddition.setText("+");
        ButtonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdditionActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonAddition);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSevenActionPerformed
        // TODO add your handling code here:
        digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonSevenActionPerformed

    private void ButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNineActionPerformed
        // TODO add your handling code here
        digitPressed(((JButton) evt.getSource()).getText());
   
    }//GEN-LAST:event_ButtonNineActionPerformed

    private void ButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonZeroActionPerformed
        // TODO add your handling code here:
        digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonZeroActionPerformed

    private void ButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOneActionPerformed
        // TODO add your handling code here:
        digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonOneActionPerformed

    private void ButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTwoActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonTwoActionPerformed

    private void ButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThreeActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonThreeActionPerformed

    private void ButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFourActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonFourActionPerformed

    private void ButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFiveActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonFiveActionPerformed

    private void ButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSixActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonSixActionPerformed

    private void ButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEightActionPerformed
        // TODO add your handling code here:
             digitPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonEightActionPerformed

    private void ButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivisionActionPerformed
        // TODO add your handling code here:
        operatorPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonDivisionActionPerformed

    private void ButtonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicationActionPerformed
        // TODO add your handling code here:
        operatorPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonMultiplicationActionPerformed

    private void ButtonSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubtractionActionPerformed
        // TODO add your handling code here:
        operatorPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonSubtractionActionPerformed

    private void ButtonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdditionActionPerformed
        // TODO add your handling code here:
        operatorPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonAdditionActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        // TODO add your handling code here:
        operatorPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void ButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPointActionPerformed
        // TODO add your handling code here:
        pointPressed(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_ButtonPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddition;
    private javax.swing.JButton ButtonDivision;
    private javax.swing.JButton ButtonEight;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonFive;
    private javax.swing.JButton ButtonFour;
    private javax.swing.JButton ButtonMultiplication;
    private javax.swing.JButton ButtonNine;
    private javax.swing.JButton ButtonOne;
    private javax.swing.JButton ButtonPoint;
    private javax.swing.JButton ButtonSeven;
    private javax.swing.JButton ButtonSix;
    private javax.swing.JButton ButtonSubtraction;
    private javax.swing.JButton ButtonThree;
    private javax.swing.JButton ButtonTwo;
    private javax.swing.JButton ButtonZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

