/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Solution;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AKIFHASAN 
 */
public class Activity_6 extends javax.swing.JFrame {

       ArrayList<Liquor> liquorList, selectedLiquorList;
    /**
     * Creates new form Activity_6
     */
    public Activity_6() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        comboBoxQuantity = new javax.swing.JComboBox<>();
        RadioMember = new javax.swing.JRadioButton();
        RadioNonMember = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemClear = new javax.swing.JMenuItem();
        menuitemsearch = new javax.swing.JMenuItem();
        menuItemList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Liquor Order System");
        setResizable(false);

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        jScrollPane1.setViewportView(textAreaOutput);

        jLabel1.setText("Quantity");

        comboBoxQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        buttonGroup1.add(RadioMember);
        RadioMember.setText("Member");

        buttonGroup1.add(RadioNonMember);
        RadioNonMember.setSelected(true);
        RadioNonMember.setText("Non-Member");

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1)
                            .addGap(30, 30, 30)
                            .addComponent(comboBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(RadioMember)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RadioNonMember)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioMember)
                    .addComponent(RadioNonMember))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuitemExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitemExit.setLabel("Exit");
        menuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemClear.setLabel("Clear");
        menuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClearActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemClear);

        menuitemsearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitemsearch.setActionCommand("Search");
        menuitemsearch.setLabel("Search");
        menuitemsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemsearchActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemsearch);

        menuItemList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemList.setLabel("List");
        menuItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemList);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClearActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you sure?");
        if(a==JOptionPane.YES_OPTION){
            reset();
        }

    }//GEN-LAST:event_menuItemClearActionPerformed

    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you sure?");
        if(a==JOptionPane.YES_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_menuitemExitActionPerformed

    private void menuitemsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemsearchActionPerformed
        // TODO add your handling code here:
        String brandName = JOptionPane.showInputDialog("Please enter a brand such as Tooheys.");
        if(brandName!=null && brandName.length()>0){
            Liquor liquor = searchBrand(brandName);
            if(liquor!=null){
                selectedLiquorList.clear();
                selectedLiquorList.add(liquor);
                textAreaOutput.setText(formatOutput(selectedLiquorList));
            }
            else{
                JOptionPane.showMessageDialog(null,"No item found. Please see the list of all items");
            }
        }
        
    }//GEN-LAST:event_menuitemsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(selectedLiquorList.isEmpty()){
            JOptionPane.showMessageDialog(null,"No item selected for order");
        }
        else{
             
        double totalItemPrice = getTotalPrice(selectedLiquorList) * Double.valueOf(String.valueOf(comboBoxQuantity.getSelectedItem()));
        if(RadioMember.isSelected()){
            totalItemPrice = totalItemPrice - (.1 * totalItemPrice);
        }
        
        String output = "Your order is "+ String.valueOf(comboBoxQuantity.getSelectedItem())+ "carton(s) of "+selectedLiquorList.get(0).brand+ "\nTotal price: "+totalItemPrice;
            JOptionPane.showMessageDialog(null,output);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListActionPerformed
        // TODO add your handling code here:
        textAreaOutput.setText(formatOutput(liquorList));
        
    }//GEN-LAST:event_menuItemListActionPerformed

    private double getTotalPrice(ArrayList<Liquor> selectedLiquorList){
        double total=0;
        for(Liquor liquor: selectedLiquorList){
            total = total+liquor.price;
        }
        return total;
    }
    
    private void reset(){
        String output="---------------------------------------------------------------------------------------------------------- \n";
        output = output + String.format(" %10s %50s %50s","Brand","Price","YearBrewed");
        output = output + "\n----------------------------------------------------------------------------------------------------------\n";
        textAreaOutput.setText(output);
        RadioNonMember.setSelected(true);
        comboBoxQuantity.setSelectedIndex(0);
         
    }
    
    private Liquor searchBrand(String brandName){
        for(Liquor liquor: liquorList){
            if(liquor.brand.trim().equalsIgnoreCase(brandName.trim())){
                return liquor;
            }
        }
        return null;
    }
    
    private void init(){
        String output="---------------------------------------------------------------------------------------------------------- \n";
        output = output + String.format(" %10s %50s %50s","Brand","Price","YearBrewed");
        output = output + "\n----------------------------------------------------------------------------------------------------------\n";
        textAreaOutput.setText(output);
       // textAreaOutput.setEnabled(false);
        liquorList = new ArrayList<Liquor>();
        liquorList.add(new Liquor("Asahi",30,"2001")); 
        liquorList.add(new Liquor("Yanjing",27,"2002")); 
        liquorList.add(new Liquor("Tooheys",33,"2000")); 
        liquorList.add(new Liquor("Heinek",35,"2004")); 
        selectedLiquorList = new ArrayList<Liquor>();
        
    }
    

    
    public class Liquor {
        public String brand = "";
        public double price = 0;
        public String yearBrewed = "";
        
        public Liquor(String brand, double price, String yearBrewed){
            this.brand = brand;
            this.price = price;
            this.yearBrewed = yearBrewed;
        }
    }
    
    private String formatOutput(ArrayList<Liquor> selectedLiquorList){
          String output="---------------------------------------------------------------------------------------------------------- \n";
        output = output + String.format(" %10s %50s %50s","Brand","Price","YearBrewed");
        output = output + "\n----------------------------------------------------------------------------------------------------------\n";
        for(Liquor liquor: selectedLiquorList){
            String formatedStr = String.format(" %10s %50s %50s",liquor.brand,liquor.price,liquor.yearBrewed);
               output= output +formatedStr+"\n";
        }
        return output;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioMember;
    private javax.swing.JRadioButton RadioNonMember;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuItemClear;
    private javax.swing.JMenuItem menuItemList;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemsearch;
    private javax.swing.JTextArea textAreaOutput;
    // End of variables declaration//GEN-END:variables
}
