/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Solution;

/**
 *
 * @author AKIFHASAN
 */
public class Activity_1 extends javax.swing.JFrame {

    /**
     * Creates new form Activity_1
     */
    public Activity_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ButtonSeven = new javax.swing.JButton();
        ButtonEight = new javax.swing.JButton();
        ButtonNine = new javax.swing.JButton();
        ButtonDivision = new javax.swing.JButton();
        ButtonFour = new javax.swing.JButton();
        ButtonFive = new javax.swing.JButton();
        ButtonSix = new javax.swing.JButton();
        ButtonMultiplication = new javax.swing.JButton();
        ButtonOne = new javax.swing.JButton();
        ButtonTwo = new javax.swing.JButton();
        ButtonThree = new javax.swing.JButton();
        ButtonSubtraction = new javax.swing.JButton();
        ButtonZero = new javax.swing.JButton();
        ButtonPoint = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonAddition = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        ButtonSeven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSeven.setText("7");
        ButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSevenActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSeven);

        ButtonEight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonEight.setText("8");
        jPanel2.add(ButtonEight);

        ButtonNine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonNine.setText("9");
        ButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNineActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonNine);

        ButtonDivision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonDivision.setText("/");
        jPanel2.add(ButtonDivision);

        ButtonFour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonFour.setText("4");
        jPanel2.add(ButtonFour);

        ButtonFive.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonFive.setText("5");
        jPanel2.add(ButtonFive);

        ButtonSix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSix.setText("6");
        jPanel2.add(ButtonSix);

        ButtonMultiplication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonMultiplication.setText("*");
        jPanel2.add(ButtonMultiplication);

        ButtonOne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonOne.setText("1");
        jPanel2.add(ButtonOne);

        ButtonTwo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonTwo.setText("2");
        jPanel2.add(ButtonTwo);

        ButtonThree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonThree.setText("3");
        jPanel2.add(ButtonThree);

        ButtonSubtraction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSubtraction.setText("-");
        jPanel2.add(ButtonSubtraction);

        ButtonZero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonZero.setText("0");
        jPanel2.add(ButtonZero);

        ButtonPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPoint.setText(".");
        jPanel2.add(ButtonPoint);

        ButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonEqual.setText("=");
        jPanel2.add(ButtonEqual);

        ButtonAddition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonAddition.setText("+");
        jPanel2.add(ButtonAddition);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSevenActionPerformed

    private void ButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNineActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddition;
    private javax.swing.JButton ButtonDivision;
    private javax.swing.JButton ButtonEight;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonFive;
    private javax.swing.JButton ButtonFour;
    private javax.swing.JButton ButtonMultiplication;
    private javax.swing.JButton ButtonNine;
    private javax.swing.JButton ButtonOne;
    private javax.swing.JButton ButtonPoint;
    private javax.swing.JButton ButtonSeven;
    private javax.swing.JButton ButtonSix;
    private javax.swing.JButton ButtonSubtraction;
    private javax.swing.JButton ButtonThree;
    private javax.swing.JButton ButtonTwo;
    private javax.swing.JButton ButtonZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
